sudo: required
language: rust

rust:
  - nightly

cache: cargo

os:
  - linux

dist: trusty

before_script:
  - sudo apt-get install -qq nasm
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
  - source ~/.cargo/env
  - rustup component add rust-src
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/rustfmt || cargo install rustfmt)
  - (test -x $HOME/.cargo/bin/xargo || cargo install xargo)
  - cargo install-update -a

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - ./configure && make
